import { useTheme } from '../context/ThemeContext';
import React, { useState } from 'react';
import { StyleSheet, Text, View, ScrollView, TouchableOpacity, LayoutAnimation, Platform, UIManager } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';

if (Platform.OS === 'android' && UIManager.setLayoutAnimationEnabledExperimental) {
  UIManager.setLayoutAnimationEnabledExperimental(true);
}

export default function TermsContentScreen() {
  const { colors, isDark } = useTheme();
  const styles = getStyles(colors, isDark);
  const router = useRouter();
  const [lang, setLang] = useState<'en' | 'so'>('en');

  const toggleLang = () => {
    LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
    setLang(lang === 'en' ? 'so' : 'en');
  };

  const content = {
    en: {
      title: "Terms & Conditions",
      lastUpdated: "Effective Date: 18/5/2026",
      subtitle: "Welcome to Darkpen. By downloading, accessing, or using the application, you agree to these Terms and Conditions. If you do not agree with these Terms, please do not use the application.",
      sections: [
        {
          heading: "1. About the App",
          text: "Darkpen is an AI-powered educational platform designed to help students:\n• Review lessons\n• Prepare for exams\n• Read educational materials\n• Practice with previous exams\n• Improve understanding of academic subjects\n• Engage in general AI conversations for learning and entertainment purposes\n\nThe app provides AI-generated responses and educational assistance."
        },
        {
          heading: "2. Eligibility",
          text: "Users must comply with all local laws and regulations while using the app.\n\nUsers under the age required by local law must use the application under parental or guardian supervision."
        },
        {
          heading: "3. Educational Use Only",
          text: "The application is intended for educational and informational purposes only.\n\nThe app is designed to support learning and revision. It is not intended to:\n• Facilitate cheating\n• Complete exams dishonestly\n• Impersonate students\n• Generate harmful, illegal, or unethical content\n• Violate school, university, or examination rules\n\nUsers are solely responsible for how they use the application."
        },
        {
          heading: "4. Academic Integrity",
          text: "Users must follow the academic policies of their schools, universities, and examination institutions.\n\nDarkpen does not encourage or support:\n• Exam cheating\n• Unauthorized assistance during tests\n• Plagiarism\n• Submission of AI-generated work as original work without permission\n\nAny misuse of the app for academic dishonesty is strictly prohibited.\n\nThe company and developers are not responsible for misuse by users."
        },
        {
          heading: "5. User Responsibility",
          text: "Users agree not to use the app to:\n• Break laws\n• Harass or abuse others\n• Share harmful or illegal content\n• Upload copyrighted material without permission\n• Attempt to hack, reverse engineer, or disrupt the service\n• Use the app for fraudulent purposes\n\nUsers are fully responsible for content they upload or generate."
        },
        {
          heading: "6. AI Limitations",
          text: "AI-generated answers may occasionally:\n• Contain mistakes\n• Be incomplete\n• Be outdated\n• Require verification\n\nUsers should independently verify important educational, academic, medical, financial, or legal information.\n\nThe app does not guarantee perfect accuracy."
        },
        {
          heading: "7. Content and Uploaded Materials",
          text: "Users may upload educational materials such as:\n• Notes\n• PDFs\n• Study guides\n• Past exams\n• Books they have permission to use\n\nUsers must only upload content they legally own or are authorized to use.\n\nThe company is not responsible for copyrighted materials uploaded by users."
        },
        {
          heading: "8. Intellectual Property",
          text: "The application, branding, design, software, and AI systems are owned by Darkpen.\n\nUsers may not:\n• Copy the app\n• Resell the service\n• Redistribute the software\n• Use branding without permission\n\nAll rights are reserved."
        },
        {
          heading: "9. User Accounts",
          text: "Users are responsible for maintaining the security of their accounts.\n\nThe company may suspend or terminate accounts that:\n• Violate these Terms\n• Abuse the platform\n• Engage in illegal or harmful activities."
        },
        {
          heading: "10. Chat and Social Features",
          text: "If the app includes AI chat, entertainment, or social-style conversations:\n• Conversations are generated by artificial intelligence\n• AI responses do not represent human opinions\n• Users should not rely on AI for emotional, medical, financial, or legal advice\n\nUsers must behave respectfully.\n\nHarassment, explicit abuse, threats, exploitation, or illegal conduct are prohibited."
        },
        {
          heading: "11. Limitation of Liability",
          text: "To the maximum extent permitted by law:\n• The app is provided “as is”\n• The company makes no guarantees regarding uninterrupted service or perfect accuracy\n• The company is not liable for academic penalties, exam results, misuse, damages, or losses caused by user behavior\n\nUsers use the app at their own risk."
        },
        {
          heading: "12. Termination",
          text: "The company may suspend or permanently remove users who violate these Terms."
        },
        {
          heading: "13. Changes to Terms",
          text: "We may update these Terms from time to time.\n\nContinued use of the app after updates means acceptance of the revised Terms."
        },
        {
          heading: "14. Contact Information",
          text: "For questions regarding these Terms:\nEmail: team.darkpen@gmail.com\nCompany: darkpen"
        }
      ]
    },
    so: {
      title: "Shuruudaha & Xeerarka",
      lastUpdated: "Taariikhda Dhaqangalka: 18/5/2026",
      subtitle: "Ku soo dhawaada Darkpen. Markaad soo dejiso, gasho, ama isticmaasho codsiga, waxaad ogolaatay Shuruudahan iyo Xeerarkan. Haddii aadan ogolayn Shuruudahan, fadlan ha isticmaalin codsiga.",
      sections: [
        {
          heading: "1. Ku Saabsan App-ka",
          text: "Darkpen waa madal waxbarasho oo ku shaqaysa AI looguna talagalay in lagu caawiyo ardayda si ay:\n• U muraajaceeyaan casharada\n• U diyaargaroobaan imtixaanada\n• U akhriyaan agabka waxbarashada\n• U ku shaqeeyaan imtixaanadii hore\n• U horumariyaan fahamka maadooyinka dugsiga\n• U sameeyaan wada-sheekaysi AI oo guud oo loogu talagalay barasho iyo madadaalo\n\nApp-ku wuxuu bixiyaa jawaabo ka soo baxay AI iyo caawinaad waxbarasho."
        },
        {
          heading: "2. U-qalmitaanka (Eligibility)",
          text: "Isticmaalayaashu waa inay u hoggaansamaan dhammaan shuruucda iyo shawaaniinta deegaanka inta ay isticmaalayaan app-ka.\n\nIsticmaalayaasha ka yar da'da sharciga deegaanku dalbado waa inay codsiga u isticmaalaan kormeerka waalidka ama mas'uulka."
        },
        {
          heading: "3. Adeegsi Waxbarasho Kaliya",
          text: "Codsiga waxaa loogu talagalay ujeedooyin waxbarasho iyo macluumaad oo kaliya.\n\nApp-ka waxaa loo naqshadeeyay si uu u taageero barashada iyo muraajacada. Looma talagalin inuu:\n• Fududeeyo qishka imtixaanka\n• Imtixaanada loo dhameeyo si aan daacad ahayn\n• Iska dhigo arday kale (Impersonate)\n• Soo saaro qoraallo waxyeello leh, sharci darro ah, ama aan anshax lahayn\n• Ku xadgudbo xeerarka dugsiga, jaamacadda, ama imtixaanka\n\nIsticmaalayaasha ayaa keliya mas'uul ka ah sida ay u isticmaalaan codsiga."
        },
        {
          heading: "4. Academic Integrity (Sharafta Dugsiga iyo Jaamacadda)",
          text: "Isticmaalayaashu waa inay raacaan siyaasadaha akadeemiyadeed ee dugsiyadooda, jaamacadaha, iyo hay'adaha imtixaanka bixiya.\n\nDarkpen ma dhiirrigeliso mana taageerto:\n• Qishka imtixaanada\n• Caawinaad aan la fasaxin inta lagu jiro imtixaanka\n• Plagiarism (Xatooyada qoraalka)\n• Gudbinta shaqada AI ay soo saartay iyadoo laga dhigayo mid asal ah fasax la'aan\n\nSi kasta oo loo isticmaalo app-ka oo la xiriirta daacad-darro waxbarasho si adag ayaa loo mamnuucay.\n\nShirkadda iyo horumariyayaashu mas'uul kama aha si qaldan u isticmaalka isticmaalayaasha."
        },
        {
          heading: "5. Mas'uuliyadda Isticmaalaha",
          text: "Isticmaalayaashu waxay ogolaadeen inaysan u isticmaalin app-ka inay:\n• Jabiyaan sharciga\n• Dhibaan ama u xadgudbaan dadka kale\n• Wadaagaan macluumaad waxyeello leh ama sharci darro ah\n• Soo upload-gareeyaan agab leh xuquuqda daabacaadda fasax la'aan\n• Isku dayaan inay jabsadaan, dib u naqshadeeyaan (reverse engineer), ama carqaladeeyaan adeegga\n• U isticmaalaan app-ka ujeedooyin khiyaano ah\n\nIsticmaalayaasha ayaa gabi ahaanba mas'uul ka ah agabka ay soo upload-gareeyaan ama ay soo saaraan."
        },
        {
          heading: "6. Xaddidaadda AI",
          text: "Jawaabaha AI ay soo saarto mararka qaar waxay:\n• Ku jiri karaan khaladaad\n• Noqon karaan kuwo qabyo ah\n• Noqon karaan kuwo duugoobay\n• U baahan karaan xaqiijin\n\nIsticmaalayaashu waa inay si madaxbannaan u xaqiijiyaan macluumaadka muhiimka ah ee waxbarasho, caafimaad, maaliyadeed, ama sharci.\n\nApp-ku ma dammaanad qaadayo saxsanaan kaamil ah."
        },
        {
          heading: "7. Agabka la soo Upload-gareeyay",
          text: "Isticmaalayaashu waxay soo upload-gareyn karaan agab waxbarasho oo ay ka mid yihiin:\n• Qoraallo\n• PDF-yo\n• Hagayaasha waxbarashada\n• Imtixaanadii hore\n• Buugaag ay u haystaan fasax inay isticmaalaan\n\nIsticmaalayaashu waa inay kaliya soo upload-gareeyaan agab ay sharciga u leeyihiin ama loo fasaxay inay isticmaalaan.\n\nShirkaddu mas'uul kama aha agabka xuquuqda daabacaadda leh ee ay soo upload-gareeyaan isticmaalayaashu."
        },
        {
          heading: "8. Xuquuqda Lahaanshaha Aqooneed (Intellectual Property)",
          text: "Codsiga, sumadda, naqshadda, software-ka, iyo nidaamyada AI waxaa iska leh Darkpen.\n\nIsticmaalayaashu ma awoodaan inay:\n• Nuqul ka sameeyaan app-ka (Copy)\n• Dib u iibiyaan adeegga\n• Dib u qaybiyaan software-ka\n• Isticmaalaan sumadda fasax la'aan\n\nDhammaan xuquuqdu waa dhowran tahay."
        },
        {
          heading: "9. Koontooyinka Isticmaalaha",
          text: "Isticmaalayaasha ayaa mas'uul ka ah ilaalinta ammaanka koontadooda.\n\nShirkaddu waxay hakin kartaa ama tirtiri kartaa koontooyinka:\n• Jabiya Shuruudahan\n• Ku xadgudba madal-ka\n• Ku lug yeesha dhaqdhaqaaqyo sharci darro ah ama waxyeello leh"
        },
        {
          heading: "10. Wada-sheekaysiga iyo Astaamaha Bulshada",
          text: "Haddii app-ku ku daro wada-sheekaysi AI, madadaalo, ama wada-hadal bulsho:\n• Wada-hadalada waxaa soo saaray sirdoonka macmalka ah (AI)\n• Jawaabaha AI ma matalaan ra'yiga aadanaha\n• Isticmaalayaashu waa inayna ku tiirsanaan AI talooyinka dareenka, caafimaadka, maaliyadda, ama sharciga\n\nIsticmaalayaashu waa inay u dhaqmaan si xushmad leh.\n\nXadgudubka, cayda cad, hanjabaadaha, ka faa'iidaysiga, ama dhaqanka sharci darrada ah waa mamnuuc."
        },
        {
          heading: "11. Limitation of Liability (Xaddidaadda Mas'uuliyadda)",
          text: "Ilaa xadka ugu sarreeya ee sharcigu oggol yahay:\n• App-ka waxaa loo bixiyaa sidii uu yahay (“as is”)\n• Shirkaddu ma bixiso wax dammaanad ah oo ku saabsan adeeg aan kala go' lahayn ama saxsanaan dhammaystiran\n• Shirkaddu mas'uul kama aha ganaaxyada dugsiga/jaamacadda, natiijooyinka imtixaanka, isticmaalka qaldan, waxyeellada, ama khasaaraha ay sababtay dhaqanka isticmaalaha\n\nIsticmaalayaashu waxay app-ka u isticmaalayaan khatartooda gaarka ah."
        },
        {
          heading: "12. Joojinta (Termination)",
          text: "Shirkaddu waxay hakin kartaa ama si joogto ah u saari kartaa isticmaalayaasha ku xadgudba Shuruudahan."
        },
        {
          heading: "13. Changes to Terms (Isbeddelada Shuruudaha)",
          text: "Waxaan cusbooneysiin karnaa Shuruudahan marba marka ka dambaysa.\n\nIsticmaalka joogtada ah ee app-ka ka dib cusbooneysiinta wuxuu ka dhigan yahay ogolaanshaha Shuruudaha la qayaxay."
        },
        {
          heading: "14. Contact Information (Macluumaadka Xiriirka)",
          text: "Wixii su'aalo ah oo ku saabsan Shuruudahan:\nEmail: team.darkpen@gmail.com\nCompany: darkpen"
        }
      ]
    }
  };

  const t = content[lang];

  return (
    <SafeAreaView style={styles.container} edges={['top', 'bottom']}>
      {/* HEADER */}
      <View style={styles.header}>
        <View style={styles.headerLeft}>
          <TouchableOpacity style={styles.backButton} onPress={() => router.back()} activeOpacity={0.7}>
            <Ionicons name="chevron-back" size={22} color={colors.secondary} />
          </TouchableOpacity>
        </View>

        <View style={styles.headerCenter}>
          <Text style={styles.headerTitle}>{t.title}</Text>
        </View>

        <View style={styles.headerRight}>
          <TouchableOpacity style={styles.langButton} onPress={toggleLang} activeOpacity={0.7}>
            <Text style={styles.langButtonText}>{lang === 'en' ? 'SO' : 'EN'}</Text>
            <Ionicons name="language-outline" size={16} color={colors.primary} />
          </TouchableOpacity>
        </View>
      </View>

      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        <View style={styles.heroSection}>
          <View style={styles.iconCircle}>
            <Ionicons name="warning" size={40} color="#EF4444" />
          </View>
          <Text style={styles.mainTitle}>{t.title}</Text>
          <Text style={styles.dateText}>{t.lastUpdated}</Text>
          <Text style={styles.subtitleText}>{t.subtitle}</Text>
        </View>

        <View style={styles.contentCard}>
          {t.sections.map((section, index) => (
            <View key={index} style={styles.section}>
              <Text style={styles.sectionHeading}>{section.heading}</Text>
              <Text style={styles.sectionText}>{section.text}</Text>
              {index < t.sections.length - 1 && <View style={styles.divider} />}
            </View>
          ))}
        </View>

        <View style={styles.footerSpacing} />
      </ScrollView>
    </SafeAreaView>
  );
}

const getStyles = (colors: any, isDark: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background, 
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.background,
    zIndex: 10,
  },
  headerLeft: {
    flex: 1,
    alignItems: 'flex-start',
  },
  headerCenter: {
    flex: 2,
    alignItems: 'center',
  },
  headerRight: {
    flex: 1,
    alignItems: 'flex-end',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.card,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.secondary,
    letterSpacing: 0.5,
  },
  langButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  langButtonText: {
    fontSize: 13,
    fontWeight: '800',
    color: colors.primary,
    marginRight: 6,
  },
  scrollContent: {
    padding: 20,
  },
  heroSection: {
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 30,
    paddingHorizontal: 10,
  },
  iconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#FEF2F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  mainTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.secondary,
    textAlign: 'center',
    marginBottom: 8,
  },
  dateText: {
    fontSize: 14,
    color: colors.textLight,
    fontWeight: '600',
    marginBottom: 12,
  },
  subtitleText: {
    fontSize: 15,
    color: isDark ? 'rgba(255, 255, 255, 0.6)' : '#475569',
    textAlign: 'center',
    lineHeight: 22,
  },
  contentCard: {
    backgroundColor: colors.card,
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  section: {
    marginBottom: 0,
  },
  sectionHeading: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.secondary,
    marginBottom: 12,
  },
  sectionText: {
    fontSize: 15,
    lineHeight: 26,
    color: isDark ? 'rgba(255, 255, 255, 0.7)' : '#475569', 
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: 24,
  },
  footerSpacing: {
    height: 40,
  }
});
